version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db

  events:
    build: events
    ports: 
      - 9000:9000
    volumes:
      - ./events:/opt/runable/events
    links:
      - mongo

volumes:
  db-data:
