version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db

  auth:
    build: auth
    ports: 
      - 9091:9091
    volumes:
      - ./auth:/opt/runable/auth

  events:
    build: events
    ports: 
      - 9090:9090
    volumes:
      - ./events:/opt/runable/events
    links:
      - mongo

volumes:
  db-data:
