swagger: "2.0"
info:
  version: "0.0.1"
  title: Runable Api
host: localhost:9000
basePath: /
 
schemes:
  # remove http once out of dev
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  $ref: "file://api/swagger/paths/index.yml"

# complex objects have schema definitions
definitions:
  $ref: "file://api/swagger/definitions/index.yml"
