FROM node:latest

WORKDIR /opt/runable/events

ADD package.json .
ADD package-lock.json .
ADD .eslintrc .

COPY . .

RUN npm install
RUN npm install -g nodemon

EXPOSE 9090

VOLUME [ "/opt/runable/events" ]

CMD ["npm", "run", "server"]