FROM node:latest

WORKDIR /opt/runable/events

ADD package.json .
ADD package-lock.json .
ADD .eslintrc .

RUN npm install && \
    npm install -g nodemon

COPY . / ./

EXPOSE 9090

VOLUME [ "/opt/runable/events" ]

CMD ["npm", "run", "server"]