FROM node:latest

WORKDIR /opt/runable/events

ADD package.json .
ADD package-lock.json .
ADD .eslintrc .

RUN npm install

COPY . .

EXPOSE 9000

VOLUME [ "/opt/runable/events" ]

CMD ["npm", "run", "server"]